package gde.gui;

import gde.gui.tablemodels.ChartTableModel;
import gde.gui.util.DatabaseHandler;
import gde.models.Chart;
import gde.models.Chart.ChartType;
import gde.models.Field;
import gde.models.Game;
import gde.service.Listener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.bson.types.ObjectId;
import org.jongo.Jongo;
import org.jongo.MongoCollection;

public class ManageChartDialog extends javax.swing.JDialog {

    private static final Jongo database = DatabaseHandler.getDatabase();
    private final Game game;
    private final JTable chartTable;
    private final boolean isCreated;

    public ManageChartDialog(Game game, JTable chartTable, boolean isCreated) {
        initComponents();
        this.game = game;
        this.chartTable = chartTable;
        this.isCreated = isCreated;
                
        MongoCollection fieldsCollection = database.getCollection("fields");
        String query = String.format("{gameId: '%s'}", game.getKey().toString());
        Iterable<Field> fields = fieldsCollection.find(query).as(Field.class);
        for (Field field : fields) {
            verticalAxisComboBox.addItem(field);
            horizontalAxisComboBox.addItem(field);
        }
        for (Chart.ChartType fieldType : Chart.ChartType.values()) {
            chartTypeComboBox.addItem(fieldType);
        }
       
        if (isCreated) {
            ChartTableModel chartTableModel = ((ChartTableModel) chartTable.getModel());
            Chart chart = chartTableModel.getEntryAt(chartTable.getSelectedRow());
            Field xAxisField = fieldsCollection.findOne(new ObjectId(chart.getxAxisFieldId())).as(Field.class);
            Field yAxisField = fieldsCollection.findOne(new ObjectId(chart.getyAxisFieldId())).as(Field.class);
            titleLabel.setText(isCreated ? "Edit Chart" : "New Chart");
            verticalAxisComboBox.setSelectedItem(yAxisField);
            horizontalAxisComboBox.setSelectedItem(xAxisField);
            chartTypeComboBox.setSelectedItem(chart.getChartType());
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        horizontalAxisLabel = new javax.swing.JLabel();
        verticalAxisComboBox = new javax.swing.JComboBox();
        horizontalAxisComboBox = new javax.swing.JComboBox();
        chartTypeComboBox = new javax.swing.JComboBox();
        chartTypeLabel = new javax.swing.JLabel();
        verticalAxisLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        horizontalAxisLabel.setText("Vertical Axis");

        chartTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chartTypeComboBoxInputStateChanged(evt);
            }
        });

        chartTypeLabel.setText("Chart Type");

        verticalAxisLabel.setText("Horizontal Axis");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        titleLabel.setText("New Chart");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(layout.createSequentialGroup()
                            .add(saveButton)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(cancelButton))
                        .add(layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(horizontalAxisLabel)
                                .add(verticalAxisLabel)
                                .add(chartTypeLabel))
                            .add(18, 18, 18)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(verticalAxisComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 222, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(horizontalAxisComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 222, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(chartTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 222, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(titleLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 338, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(4, 4, 4)
                .add(titleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(horizontalAxisLabel)
                    .add(verticalAxisComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(verticalAxisLabel)
                    .add(horizontalAxisComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(chartTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(chartTypeLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(saveButton)
                    .add(cancelButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chartTypeComboBoxInputStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chartTypeComboBoxInputStateChanged
        horizontalAxisComboBox.setEnabled(chartTypeComboBox.getSelectedItem() != ChartType.PIE);
    }//GEN-LAST:event_chartTypeComboBoxInputStateChanged

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.setVisible(false);

        Field verticalAxis = ((Field) verticalAxisComboBox.getSelectedItem());
        Field horizontalAxis = ((Field) horizontalAxisComboBox.getSelectedItem());
        ChartType chartType = (ChartType) chartTypeComboBox.getSelectedItem();
        
        Chart newChart = new Chart(
                String.format(verticalAxis.getName() + "%s",
                    (chartType != Chart.ChartType.PIE ? " vs. " + horizontalAxis.getName(): " Distribution")),
                horizontalAxis.getKey().toString(),
                verticalAxis.getKey().toString(),
                (ChartType) chartTypeComboBox.getSelectedItem(),
                game.getKey().toString());

        ChartTableModel chartTableModel = ((ChartTableModel) chartTable.getModel());
        if (isCreated) {
            chartTableModel.update(newChart, chartTable.getSelectedRow());
        } else {
            chartTableModel.add(newChart);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (isCreated) {
            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want cancel your changes?", "Confirm Cancellation",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                this.setVisible(false);
            }
        } else {
            this.setVisible(false);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox chartTypeComboBox;
    private javax.swing.JLabel chartTypeLabel;
    private javax.swing.JComboBox horizontalAxisComboBox;
    private javax.swing.JLabel horizontalAxisLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox verticalAxisComboBox;
    private javax.swing.JLabel verticalAxisLabel;
    // End of variables declaration//GEN-END:variables
}
